### ISSUE TITLE
Edit start date ann end date of holiday

### ISSUE THREAD

**Issue by giangnt55** [khoahd7621/salary-management-ui#4]
Action: edit valentine holiday: from 14/2/2023 to 14/2/2023

**Comment by khoahd7621** [comment]
I can't catch up on your issue. Please give me more details.

**Comment by giangnt55** [comment]
**Context**: In edit holiday screen, choose start date: 14/02/2023, and end date 14/02/2023 also, click save.

**Expected** : the updated holiday has start date 14/02/2023 to end date 14/02/2023

**Reality** : The updated one has start date 13/02/2023 to end date 13/02/2023

**Comment by khoahd7621** [comment]
Thanks. I got your point. I'll try to figure out what exactly is wrong here.
